<?php
/**
 * @file
 * Interface module for talking with the materials backend.
 */

define('BUTTON_URL', 'http://bibliotek.dk/da/export/cart/ris/');

/**
 * Implements hook_block_info().
 */

function ding_export_to_ris_block_info() {
  $blocks['export_to_ris'] = array(
    'info' => t('Export in RIS-format'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */

function ding_export_to_ris_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'export_to_ris':
      $module_path = drupal_get_path('module', 'ding_export_to_ris');
      // Export bookmarts settings to Drupal js settings.
      drupal_add_js(array('exportToRisUrl' => BUTTON_URL), 'setting');
      // Enabling ding popup for error messaging.
      drupal_add_js(drupal_get_path('module', 'ding_popup') . '/ding_popup.js');
      drupal_add_js($module_path . '/js/ding_export_to_ris.js', array(
        'scope' => 'footer',
        'weight' => 99,
      ));

      // Block markup.
      $block['subject'] = t('Export in RIS-format');
      $block['content'] = l(
        t('Export in RIS-format'), '#',
        array(
          'attributes' =>
            array(
              'class' => array('export-to-ris')
            )
        )
      );

      break;
  }
  return $block;
}

/**
 * Implements hook_ding_entity_buttons().
 */
function ding_export_to_ris_ding_entity_buttons($type, $entity, $widget = 'default') {
  $id = $entity->ding_entity_id;
  if (!empty($entity->data)) {
    $object = $entity->data;
    $id = $object->getObjectId();
  }
  return array(
    array(
      '#theme' => 'link',
      '#text' => '<i class="icon-white icon-download-alt"></i>',
      '#path' => '#',
      '#weight' => 104,
      '#options' => array(
        'attributes' => array(
          'class' => array(
            'btn',
            'btn-artesis-turquoise',
            'export-to-ris-btn',
          ),
          'data-tid' => $id,
          'title' => t('Export in RIS-format'),
        ),
        'html' => TRUE,
        'absolute' => TRUE,
      ),
      '#attached' => array(
        'js' => array(
          array(
            'data' => drupal_get_path('module', 'ding_export_to_ris') . '/js/ding_export_to_ris.js',
            'type' => 'file',
          ),
          array(
            'data' => array(
              'exportToRisUrl' => BUTTON_URL
            ),
            'type' => 'setting',
          ),
        ),
      ),
    )
  );
}
